### ISSUE TITLE
Some Foreignkeys and Primary keys are missing in fillables

### ISSUE THREAD

**Issue by sridamagit** [reliese/laravel#48] opened 2017-11-24 08:01 UTC
As they are missing, not able to create rows with missing columns

Can anyone tell us how to solve this problem

**Comment by CristianLlanos** [comment] 2017-11-24 17:30
Would you mind giving some examples in order to reproduce this error?

**Comment by CristianLlanos** [comment] 2017-12-01 18:35
Without any examples no one would be able to fix this.

**Comment by CristianLlanos** [comment] 2018-05-18 02:44
I'm closing this issue since there is no information on how to replicate the error.

**Closed by CristianLlanos** 2018-05-18 02:44 UTC
