### ISSUE TITLE
incompatible to php 7.2

### ISSUE THREAD

**Issue by Jossnaz** [reliese/laravel#82] opened 2018-04-04 23:45 UTC
caused by
https://secure.php.net/manual/en/migration72.incompatible.php

look for `count(`

error

```

In Model.php line 684:
                                                                              
  [ErrorException]                                                            
  count(): Parameter must be an array or an object that implements Countable  
                                                                              

Exception trace:


Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 count() at /home/myuser/IdeaProjects/ myproject/src/vendor/reliese/laravel/src/Coders/Model/Model.php:684
 Reliese\Coders\Model\Model->hasCustomPrimaryKey() at /home/myuser/IdeaProjects/ myproject/src/vendor/reliese/laravel/src/Coders/Model/Factory.php:309
 Reliese\Coders\Model\Factory->body() at /home/myuser/IdeaProjects/ myproject/src/vendor/reliese/laravel/src/Coders/Model/Factory.php:233
 Reliese\Coders\Model\Factory->fillTemplate() at /home/myuser/IdeaProjects/ myproject/src/vendor/reliese/laravel/src/Coders/Model/Factory.php:148
 Reliese\Coders\Model\Factory->create() at /home/myuser/IdeaProjects/ myproject/src/vendor/reliese/laravel/src/Coders/Model/Factory.php:118
 Reliese\Coders\Model\Factory->map() at /home/myuser/IdeaProjects/ myproject/src/vendor/reliese/laravel/src/Coders/Console/CodeModelsCommand.php:69
 Reliese\Coders\Console\CodeModelsCommand->handle() at n/a:n/a
 call_user_func_array() at /home/myuser/IdeaProjects/ myproject/src/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/myuser/IdeaProjects/ myproject/src/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/myuser/IdeaProjects/ myproject/src/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/myuser/IdeaProjects/ myproject/src/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /home/myuser/IdeaProjects/ myproject/src/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
 Illuminate\Console\Command->execute() at /home/myuser/IdeaProjects/ myproject/src/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /home/myuser/IdeaProjects/ myproject/src/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
 Illuminate\Console\Command->run() at /home/myuser/IdeaProjects/ myproject/src/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /home/myuser/IdeaProjects/ myproject/src/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /home/myuser/IdeaProjects/ myproject/src/vendor/symfony/console/Application.php:148
```

**Comment by jefhar** [comment] 2018-05-16 00:17
Possible duplicate of #92

**Comment by CristianLlanos** [comment] 2018-05-18 02:40
This problem should happend anymore thanks to #93. I'll try to make a release soon. However, you can have the new changes by importing the development version of this package. Hopefully nothing will break :D

**Comment by mixartemev** [comment] 2018-09-22 20:02
Why you didn't close this issue?

**Comment by CristianLlanos** [comment] 2018-09-24 04:16
Closing the issue.

**Closed by CristianLlanos** 2018-09-24 04:16 UTC
Labels: bug
